### ISSUE TITLE
c-i-f behavior broken/unexpected

### ISSUE THREAD

**Issue by JoshPaulie** [RodrigoScola/vscode-text-objects#1]
When I use `c-i-f`, instead of deleting and opening insert mode, the plugin simply visually select the inner function. I have to then press `c` one more time to change the contents

Another way of putting it is `v-i-f` and `c-i-f` are currently functionally the same.

Only tested for Python.

**Comment by RodrigoScola** [comment]
Hey there! Thank you for reporting! How are you enjoying the extension so far?

The issue was the way that it was handling the configuration of vimEnabled. An old idea that i had where it also checked if the vim extension was also installed. 

Just deleted it and the bug should be fixed in the new version 0.1.25

**Comment by JoshPaulie** [comment]
> How are you enjoying the extension so far?
So far so good! It'd be nice if I could just enable all of the default key maps, rather than having to copy + paste the example

> Just deleted it and the bug should be fixed in the new version 0.1.25
Sweet! Well done. Thanks for quick resolution

**Comment by RodrigoScola** [comment]
Awesome to hear that!

I'll see what I can do to add the vim keybinds!

Thank you!
